{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Documentation: https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-voices"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 0. Install Dependencies"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: ibm_watson in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (4.5.0)\n",
      "Requirement already satisfied: python-dateutil>=2.5.3 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from ibm_watson) (2.8.0)\n",
      "Requirement already satisfied: requests<3.0,>=2.0 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from ibm_watson) (2.22.0)\n",
      "Requirement already satisfied: websocket-client==0.48.0 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from ibm_watson) (0.48.0)\n",
      "Requirement already satisfied: ibm-cloud-sdk-core==1.5.1 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from ibm_watson) (1.5.1)\n",
      "Requirement already satisfied: six>=1.5 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.5.3->ibm_watson) (1.12.0)\n",
      "Requirement already satisfied: idna<2.9,>=2.5 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from requests<3.0,>=2.0->ibm_watson) (2.8)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from requests<3.0,>=2.0->ibm_watson) (1.24.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from requests<3.0,>=2.0->ibm_watson) (2019.9.11)\n",
      "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from requests<3.0,>=2.0->ibm_watson) (3.0.4)\n",
      "Requirement already satisfied: PyJWT>=1.7.1 in /Users/nicholasrenotte/opt/anaconda3/lib/python3.7/site-packages (from ibm-cloud-sdk-core==1.5.1->ibm_watson) (1.7.1)\n"
     ]
    }
   ],
   "source": [
    "!pip install ibm_watson"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 1. Authenticate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ibm_watson import TextToSpeechV1\n",
    "from ibm_cloud_sdk_core.authenticators import IAMAuthenticator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "apikey = 'YOUR API KEY'\n",
    "url = 'YOUR SERVICE URL'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Setup Service\n",
    "authenticator = IAMAuthenticator(apikey)\n",
    "tts = TextToSpeechV1(authenticator=authenticator)\n",
    "tts.set_service_url(url)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Convert with A Basic Language Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('./speech.mp3', 'wb') as audio_file:\n",
    "    res = tts.synthesize('Hello World!', accept='audio/mp3', voice='en-US_AllisonV3Voice').get_result()\n",
    "    audio_file.write(res.content)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Reading from a File "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('churchill.txt', 'r') as f:\n",
    "    text = f.readlines()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [],
   "source": [
    "text = [line.replace('\\n','') for line in text]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "text = ''.join(str(line) for line in text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('./winston.mp3', 'wb') as audio_file:\n",
    "    res = tts.synthesize(text, accept='audio/mp3', voice='en-GB_JamesV3Voice').get_result()\n",
    "    audio_file.write(res.content)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Convert with a Different Language Model"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Effects of adding Punctuation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "  \"voices\": [\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_LisaV2Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Lisa: American English female voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_LisaV2Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"de-DE_BirgitV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Birgit: Standard German (Standarddeutsch) female voice. Dnn technology.\",\n",
      "      \"language\": \"de-DE\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/de-DE_BirgitV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"es-LA_SofiaVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Sofia: Latin American Spanish (espa\\u00f1ol latinoamericano) female voice.\",\n",
      "      \"language\": \"es-LA\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/es-LA_SofiaVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_LisaV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Lisa: American English female voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_LisaV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"fr-FR_ReneeV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Renee: French (fran\\u00e7ais) female voice. Dnn technology.\",\n",
      "      \"language\": \"fr-FR\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/fr-FR_ReneeV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_KevinV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Kevin: American English male voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_KevinV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_AllisonV2Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Allison: American English female voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_AllisonV2Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"de-DE_ErikaV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Erika: Standard German (Standarddeutsch) female voice. Dnn technology.\",\n",
      "      \"language\": \"de-DE\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/de-DE_ErikaV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"ja-JP_EmiV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Emi: Japanese (\\u65e5\\u672c\\u8a9e) female voice. Dnn technology.\",\n",
      "      \"language\": \"ja-JP\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/ja-JP_EmiV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"it-IT_FrancescaV2Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Francesca: Italian (italiano) female voice. Dnn technology.\",\n",
      "      \"language\": \"it-IT\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/it-IT_FrancescaV2Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"de-DE_DieterV2Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Dieter: Standard German (Standarddeutsch) male voice. Dnn technology.\",\n",
      "      \"language\": \"de-DE\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/de-DE_DieterV2Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_HenryV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Henry: American English male voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_HenryV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"de-DE_BirgitV2Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Birgit: Standard German (Standarddeutsch) female voice. Dnn technology.\",\n",
      "      \"language\": \"de-DE\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/de-DE_BirgitV2Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"pt-BR_IsabelaV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Isabela: Brazilian Portuguese (portugu\\u00eas brasileiro) female voice. Dnn technology.\",\n",
      "      \"language\": \"pt-BR\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/pt-BR_IsabelaV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_EmilyV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Emily: American English female voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_EmilyV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_AllisonV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Allison: American English female voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_AllisonV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"es-US_SofiaV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Sofia: North American Spanish (espa\\u00f1ol norteamericano) female voice. Dnn technology.\",\n",
      "      \"language\": \"es-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/es-US_SofiaV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"es-ES_EnriqueV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Enrique: Castilian Spanish (espa\\u00f1ol castellano) male voice. Dnn technology.\",\n",
      "      \"language\": \"es-ES\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/es-ES_EnriqueV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"de-DE_DieterV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Dieter: Standard German (Standarddeutsch) male voice. Dnn technology.\",\n",
      "      \"language\": \"de-DE\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/de-DE_DieterV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"it-IT_FrancescaV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Francesca: Italian (italiano) female voice. Dnn technology.\",\n",
      "      \"language\": \"it-IT\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/it-IT_FrancescaV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"pt-BR_IsabelaVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Isabela: Brazilian Portuguese (portugu\\u00eas brasileiro) female voice.\",\n",
      "      \"language\": \"pt-BR\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/pt-BR_IsabelaVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_MichaelV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Michael: American English male voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_MichaelV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"es-LA_SofiaV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Sofia: Latin American Spanish (espa\\u00f1ol latinoamericano) female voice. Dnn technology.\",\n",
      "      \"language\": \"es-LA\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/es-LA_SofiaV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"fr-FR_NicolasV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Nicolas: French (fran\\u00e7ais) male voice. Dnn technology.\",\n",
      "      \"language\": \"fr-FR\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/fr-FR_NicolasV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-GB_KateV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Kate: British English female voice. Dnn technology.\",\n",
      "      \"language\": \"en-GB\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-GB_KateV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_OliviaV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Olivia: American English female voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_OliviaV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"es-ES_LauraV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Laura: Castilian Spanish (espa\\u00f1ol castellano) female voice. Dnn technology.\",\n",
      "      \"language\": \"es-ES\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/es-ES_LauraV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-GB_JamesV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"James: British English male voice. Dnn technology.\",\n",
      "      \"language\": \"en-GB\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-GB_JamesV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-US_MichaelV2Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Michael: American English male voice. Dnn technology.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_MichaelV2Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-GB_CharlotteV3Voice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Charlotte: British English female voice. Dnn technology.\",\n",
      "      \"language\": \"en-GB\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-GB_CharlotteV3Voice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"en-GB_KateVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Kate: British English female voice.\",\n",
      "      \"language\": \"en-GB\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-GB_KateVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": true\n",
      "      },\n",
      "      \"name\": \"en-US_AllisonVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Allison: American English female voice.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_AllisonVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"es-ES_EnriqueVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Enrique: Castilian Spanish (espa\\u00f1ol castellano) male voice.\",\n",
      "      \"language\": \"es-ES\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/es-ES_EnriqueVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"de-DE_BirgitVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Birgit: Standard German (Standarddeutsch) female voice.\",\n",
      "      \"language\": \"de-DE\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/de-DE_BirgitVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"fr-FR_ReneeVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Renee: French (fran\\u00e7ais) female voice.\",\n",
      "      \"language\": \"fr-FR\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/fr-FR_ReneeVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": true\n",
      "      },\n",
      "      \"name\": \"en-US_MichaelVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Michael: American English male voice.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_MichaelVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": true\n",
      "      },\n",
      "      \"name\": \"en-US_LisaVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Lisa: American English female voice.\",\n",
      "      \"language\": \"en-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/en-US_LisaVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"es-ES_LauraVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Laura: Castilian Spanish (espa\\u00f1ol castellano) female voice.\",\n",
      "      \"language\": \"es-ES\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/es-ES_LauraVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"es-US_SofiaVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Sofia: North American Spanish (espa\\u00f1ol norteamericano) female voice.\",\n",
      "      \"language\": \"es-US\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/es-US_SofiaVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"de-DE_DieterVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Dieter: Standard German (Standarddeutsch) male voice.\",\n",
      "      \"language\": \"de-DE\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/de-DE_DieterVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"it-IT_FrancescaVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Francesca: Italian (italiano) female voice.\",\n",
      "      \"language\": \"it-IT\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/it-IT_FrancescaVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"name\": \"ja-JP_EmiVoice\",\n",
      "      \"customizable\": true,\n",
      "      \"description\": \"Emi: Japanese (\\u65e5\\u672c\\u8a9e) female voice.\",\n",
      "      \"language\": \"ja-JP\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/ja-JP_EmiVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": false,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"customizable\": false,\n",
      "      \"name\": \"ar-AR_OmarVoice\",\n",
      "      \"description\": \"Omar: Arabic male voice.\",\n",
      "      \"language\": \"ar-AR\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/ar-AR_OmarVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"customizable\": true,\n",
      "      \"name\": \"ko-KR_YoungmiVoice\",\n",
      "      \"description\": \"Youngmi: Korean female voice.\",\n",
      "      \"language\": \"ko-KR\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/ko-KR_YoungmiVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"customizable\": true,\n",
      "      \"name\": \"ko-KR_YunaVoice\",\n",
      "      \"description\": \"Yuna: Korean female voice.\",\n",
      "      \"language\": \"ko-KR\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/ko-KR_YunaVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"customizable\": true,\n",
      "      \"name\": \"nl-NL_EmmaVoice\",\n",
      "      \"description\": \"Emma: Dutch female voice.\",\n",
      "      \"language\": \"nl-NL\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/nl-NL_EmmaVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"customizable\": true,\n",
      "      \"name\": \"nl-NL_LiamVoice\",\n",
      "      \"description\": \"Liam: Dutch male voice.\",\n",
      "      \"language\": \"nl-NL\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/nl-NL_LiamVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"customizable\": true,\n",
      "      \"name\": \"zh-CN_LiNaVoice\",\n",
      "      \"description\": \"Li Na: Chinese (Mandarin) female voice.\",\n",
      "      \"language\": \"zh-CN\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/zh-CN_LiNaVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"male\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"customizable\": true,\n",
      "      \"name\": \"zh-CN_WangWeiVoice\",\n",
      "      \"description\": \"Wang Wei: Chinese (Mandarin) male voice.\",\n",
      "      \"language\": \"zh-CN\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/zh-CN_WangWeiVoice\"\n",
      "    },\n",
      "    {\n",
      "      \"gender\": \"female\",\n",
      "      \"supported_features\": {\n",
      "        \"custom_pronunciation\": true,\n",
      "        \"voice_transformation\": false\n",
      "      },\n",
      "      \"customizable\": true,\n",
      "      \"name\": \"zh-CN_ZhangJingVoice\",\n",
      "      \"description\": \"Zhang Jing: Chinese (Mandarin) female voice.\",\n",
      "      \"language\": \"zh-CN\",\n",
      "      \"url\": \"https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/35240cd7-e4cb-4350-b640-ab650ad26480/v1/voices/zh-CN_ZhangJingVoice\"\n",
      "    }\n",
      "  ]\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "voices = tts.list_voices().get_result()\n",
    "print(json.dumps(voices, indent=2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Frere Jacque\n",
    "frere = \"\"\"Frère Jacques\n",
    "    Frère Jacques\n",
    "    Dormez-vous?\n",
    "    Dormez-vous?\n",
    "    Sonnez les matines\n",
    "    Sonnez les matines\n",
    "    Ding, ding, dong\n",
    "    Ding, ding, dong\n",
    "    Frère Jacques\n",
    "    Frère Jacques\n",
    "    Dormez-vous?\n",
    "    Dormez-vous?\n",
    "    Sonnez les matines\n",
    "    Sonnez les matines\n",
    "    Ding, ding, dong\n",
    "    Ding, ding, dong\n",
    "    Ding, ding, dong\n",
    "    Ding, ding, dong\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('./frere.mp3', 'wb') as audio_file:\n",
    "    res = tts.synthesize(frere, accept='audio/mp3', voice='fr-FR_ReneeV3Voice').get_result()\n",
    "    audio_file.write(res.content)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
